---
platform: linux
image_resource:
  type: registry-image
  source:
    repository: springci/start-site-ci-image
    tag: main
    username: ((docker-hub-username))
    password: ((docker-hub-password))
inputs:
  - name: artifactory-repo
  - name: git-repo
outputs:
  - name: blob-url
params:
  ARTIFACTORY_SERVER:
  ARTIFACTORY_REPO:
run:
  path: git-repo/ci/scripts/get-blob-url.sh